### ISSUE TITLE
Rectify the error while toggling between the normal mode and the dark mode

### ISSUE THREAD

**Issue by arpitnigam45** [acmpesuecc/ImageCompressor#2]
Add a CSS linear-gradient while toggling between the dark mode and normal mode by filling at least 2 colors in between the first color which should be Hex #060af1 30%, and the last Hex #222 80% once  you finish that our dark mode toggler is up and running

**Comment by anushkadeshpande** [comment]
Can I try solving this issue?

**Comment by arpitnigam45** [comment]
go ahead if you need any help regarding the issue do reach out to me on the discord project group for image compressor

**Comment by shivam23rawat** [comment]
I have fixed the issue pls check and accept PR . Thanks
