### ISSUE TITLE
Create An Alert

### ISSUE THREAD

**Issue by arpitnigam45** [acmpesuecc/ImageCompressor#3]
Once the compressed image gets downloaded trigger an alert and notify the user with a suitable message

**Comment by slytherin20** [comment]
Hi @arpitnigam45,
Can I work on this issue?

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
Can I work on this issue, I am new to open-source and would like to contribute

**Comment by arpitnigam45** [comment]
Assigned

**Comment by anushkadeshpande** [comment]
Can I try working on this?

**Comment by arpitnigam45** [comment]
go ahead, I have assigned the following issue to you

**Comment by shivam23rawat** [comment]
I have completed it and pushed a PR pls check .

**Comment by abhishek-pes** [comment]
@arpitnigam45  I would like to work on this

**Comment by arpitnigam45** [comment]
Assigned
